CREATE TYPE "level" AS ENUM (
  'beginner',
  'intermediate',
  'advanced'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "age" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "description" text,
  "level" level NOT NULL,
  "teacher" varchar(255) NOT NULL,
  "user_id" int
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "url" varchar NOT NULL,
  "course_id" INTEGER
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "course_id" INTEGER
);

ALTER TABLE "courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");




INSERT INTO Users (name, email, password, age) VALUES
    ('Sahid kick', 'sahidkick@academlo.com', '123456789', 25),
    ('Junior Pacheco', 'juniorpacheco@example.com', '987654321', 30);
   

   
INSERT INTO courses (title, description, level, teacher, user_id) VALUES
    ('Introduction to Programming', 'Learn the basics of programming', 'beginner', 'Mishael Caro', 1),
    ('Data Science Fundamentals', 'Explore the world of data science', 'intermediate', 'Tatiana Alvarex', 2);
   
   INSERT INTO course_videos (title, url, course_id) VALUES
    ('Introduction to Python', 'https://www.youtube.com/watch?v=rfscVS0vtbw', 5),
    ('Data Cleaning Techniques', 'https://www.youtube.com/watch?v=YzjoSo5A5RE', 6);
   
   INSERT INTO categories (name, course_id) VALUES
    ('Computer Science', 5),
    ('Data Science', 6);
   
